# Generated by Django 5.1.7 on 2025-03-23 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wine', models.IntegerField()),
                ('alcohol', models.FloatField()),
                ('malate', models.FloatField()),
                ('ash', models.FloatField()),
                ('acl', models.FloatField()),
                ('mg', models.IntegerField()),
                ('phenols', models.FloatField()),
                ('flavanoids', models.FloatField()),
                ('nonflavanoids', models.FloatField()),
                ('proanth', models.FloatField()),
                ('color', models.FloatField()),
                ('hue', models.FloatField()),
                ('OD', models.FloatField()),
                ('proline', models.IntegerField()),
            ],
        ),
    ]
